# ==============================================================================
# CONSTANTES CRIPTOGRÁFICAS Y DE CONFIGURACIÓN DEL PANEL DE INTERFAZ K4
# ==============================================================================
K4_CIPHERTEXT = "OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWTQSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR"

# Textos Planos Confirmados K1-K3
K1_PLAINTEXT = "BETWEEN SUBTLE SHADING AND THE ABSENCE OF LIGHT LIES THE NUANCE OF IQLUSION"
K2_PLAINTEXT = "IT WAS TOTALLY INVISIBLE HOWS THAT POSSIBLE ?"
K3_PLAINTEXT = "SLOWLY DESPERATELY SLOWLY THE REMAINS OF PASSAGE DEBRIS THAT ENCUMBERED THE LOWER PART OF THE DOORWAY WAS REMOVED"

# Alfabetos
ALPHABET_AZ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
KRYPTOS_ALPHABET = "KRYPTOSABCDEFGHIJLMNQUVWXZ"

# Configuración Dinámica Neon Matrix & Berlin Clock
BERLIN_CLOCK_INITIAL_STATE = "00:00"
BERLIN_CLOCK_STATUS = "ALL LAMPS OFF - STANDBY"

NEON_MATRIX_NODES = {
    "MAIN_POOL": ["0.png", "1.png", "2.png", "3.png", "4.png", "5.png", "6.png", "7.png"],
    "MASTER_NODE": "8.png"
}

# Helpers para tu orquestador
HILL_MATRICES = ["0.png", "1.png"]  # Alpha, Beta - Beta activa en CIAN como viste
TRANSPOSITION_MATRICES = ["2.png", "3.png"]
BERLIN_BYTES = ["4.png", "5.png", "6.png"]
LFSR_MASK = "7.png"
SUBSTITUTION_TABLEAU = "8.png"
